/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

/**
 *
 * @author arch1
 */
public class portada extends javax.swing.JPanel {

    /**
     * Creates new form portada
     */
    public portada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen = new javax.swing.JLabel();
        Estudiante = new javax.swing.JLabel();
        carnet = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Veterinaria.png"))); // NOI18N

        Estudiante.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Estudiante.setForeground(new java.awt.Color(0, 102, 102));
        Estudiante.setText("Roman Mendoza");

        carnet.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        carnet.setForeground(new java.awt.Color(0, 102, 102));
        carnet.setText("r3mabsnss04@gmail.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(carnet))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(Estudiante))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(imagen)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Estudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carnet)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estudiante;
    private javax.swing.JLabel carnet;
    private javax.swing.JLabel imagen;
    // End of variables declaration//GEN-END:variables
}
